version: '3.8'

services:
  # ----------------------------------------------------
  # ROBÔ 1: Planilha e Relatório Semanal
  # ----------------------------------------------------
  bot-sheets:
    build:
      context: .
      dockerfile: sheetsAutomation/Dockerfile
    container_name: jca_sheets_bot
    restart: always
    network_mode: "host"
    environment:
    # 
      - TZ=America/Sao_Paulo
    volumes:
      # Monta o .env e o arquivo de credenciais para a aplicação ler as variáveis de ambiente
      - ./.env:/app/.env
      - ./sheetsAutomation/google_credentials.json:/app/google_credentials.json

  # ----------------------------------------------------
  # ROBÔ 2: Fechamento Customer Success
  # ----------------------------------------------------
  bot-cs:
    build:
      context: .
      dockerfile: customersuccessAutomation/Dockerfile
    container_name: jca_cs_bot
    restart: always
    network_mode: "host"
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./.env:/app/.env
